PersonalBlog/Models/Category.cs
namespace PersonalBlog.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string? Description { get; set; }

        public IEnumerable<Post> posts { get; set; } 
            = new HashSet<Post>();
    }
}

PersonalBlog/Models/ErrorViewModel.cs
namespace PersonalBlog.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PersonalBlog/Models/Post.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PersonalBlog.Models
{
    /*
        for setting constraints 
        1-by Convention (Id)
        2-Data Annotation [Key]
        3- Fulent Api
     
     */
    public class Post
    {
        
        public int Id { get; set; }
        public string Title { get; set; }

        public string Content { get; set; }
        
        public  string imageUrl { get; set; }
        public int LikeCount { get; set; } = 0;
        public int DisLikeCount { get; set; } = 0;

        public DateTime CreatedAt { get; set; }

        [ForeignKey(nameof(category))]
        public int CategoryId { get; set; }
        public Category category { get; set; }
    }
}

PersonalBlog/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using PersonalBlog.Context;

namespace PersonalBlog.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _context; 

        public CategoryController(ApplicationDbContext context)
        {
            _context = context;    
        }
        public IActionResult Index()
        {
            var cats = _context.categories.ToList();


            return View(cats);
        }

        public IActionResult Details()
        {
            return View();
        }
    }
}

PersonalBlog/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using PersonalBlog.Models;

namespace PersonalBlog.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PersonalBlog/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using PersonalBlog.Context;
using PersonalBlog.Models;

namespace PersonalBlog.Controllers
{
    public class PostController : Controller
    {
        private readonly ApplicationDbContext _context;
        public PostController(ApplicationDbContext context)
        {
            _context = context;
        }
        // all posts 
        public IActionResult Index()
        {
            var posts = _context.posts.ToList();
            return View(posts);
        }

        // get one post by id 
        public IActionResult GetById(int id)
        {
            // make operations database transactions 
            return View();
        }

        public IActionResult CreatePost(Post pst)
        {
            // make operations database transactions 
            return View();
        }

    }
}

PersonalBlog/Views/Category/Create.cshtml
@*
   For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
   
}
@model Category
<div class="container">

</div>

PersonalBlog/Views/Category/Details.cshtml
<h3>hello from category details </h3>

PersonalBlog/Views/Category/Index.cshtml
@model List<Category> ;


@if (Model.Count()>0)
{
    <table class="table table-hover ">
            <thead>
                <tr>
                    <th>
                        Category Name
                    </th>
                    <th>Category Description</th>
                </tr>
            </thead>
        <tbody>
    @foreach (var item in Model)
    {
            
            
            <tr>
                 <td>@item.Name</td>  
                 <td>@item.Description</td>
            </tr>
    }
        </tbody>

    </table>

}
else
{
    <div class="container">
        <h3 class="alert alert-primary">No Category yet  </h3>
    </div>

}

PersonalBlog/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PersonalBlog/Views/Post/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="container text-center bg-primary">
    <h3>hello from posts </h3>
</div>

PersonalBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PersonalBlog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @* <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" /> *@
    
    <link rel="stylesheet" href="~/PersonalBlog.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PersonalBlog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="index">Posts</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark " asp-controller="Category" asp-action="Index">Categories </a>
                        </li>
                        <li>
                            <a class="nav-link text-dark " asp-controller="Category" asp-action="Details"> Categories Details </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - PersonalBlog - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>